version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise:10.0.3-ubuntu
    container_name: grafana
    restart: unless-stopped
    environment:
      - PGSSLMODE=require
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data: {}