definitions:
  form.CreateProjectBusinessIndicatorForm:
    properties:
      age:
        description: age
        type: integer
      change:
        description: change
        type: string
      facilities:
        description: facilities
        type: string
      issue:
        description: issue
        type: string
      projectCode:
        description: projectCode
        type: string
      qualitativeDescription:
        description: qualitativeDescription
        type: string
      quantitativeAssessment:
        description: quantitativeAssessment
        type: string
    required:
    - projectCode
    type: object
  form.CreateUserForm:
    properties:
      name:
        description: name
        type: string
      uid:
        description: uid
        type: string
    type: object
  form.UpProjectBusinessIndicatorForm:
    properties:
      age:
        description: age
        type: integer
      change:
        description: change
        type: string
      facilities:
        description: facilities
        type: string
      issue:
        description: issue
        type: string
      projectCode:
        description: projectCode
        type: string
      qualitativeDescription:
        description: qualitativeDescription
        type: string
      quantitativeAssessment:
        description: quantitativeAssessment
        type: string
    type: object
  form.UpUserForm:
    properties:
      name:
        description: name
        type: string
      uid:
        description: uid
        type: string
    type: object
  response.ErrMsgData:
    properties:
      details:
        type: object
      errCode:
        type: integer
      errMsg:
        type: string
    type: object
  response.Meta:
    additionalProperties: true
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        $ref: '#/definitions/response.ErrMsgData'
      message:
        type: string
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
info:
  contact: {}
paths:
  /api/v1/project_business_indicators:
    get:
      consumes:
      - application/json
      description: get ProjectBusinessIndicator batch record
      parameters:
      - description: Facilities
        in: query
        name: facilities
        type: string
      - description: QualitativeDescription
        in: query
        name: qualitativeDescription
        type: string
      - description: Issue
        in: query
        name: issue
        type: string
      - description: QuantitativeAssessment
        in: query
        name: quantitativeAssessment
        type: string
      - description: Change
        in: query
        name: change
        type: string
      - description: 'example: ageMap[>]=some value&ageMap[<]=some value; key must
          be >,>=,<,<=,!=,=,gt,ge,lt,le,ne,eq'
        in: query
        name: ageMap
        type: string
      - description: 'example: orderMap[column]=desc'
        in: query
        name: orderMap
        type: string
      - description: page size
        in: query
        name: pageSize
        type: integer
      - description: page num
        in: query
        name: pageNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get ProjectBusinessIndicator batch record
      tags:
      - ProjectBusinessIndicator
    post:
      consumes:
      - application/json
      description: create ProjectBusinessIndicator one record
      parameters:
      - description: 添加ProjectBusinessIndicator表单
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/form.CreateProjectBusinessIndicatorForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: create ProjectBusinessIndicator one record
      tags:
      - ProjectBusinessIndicator
  /api/v1/project_business_indicators/:id:
    delete:
      consumes:
      - application/json
      description: delete ProjectBusinessIndicator one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: delete ProjectBusinessIndicator one record
      tags:
      - ProjectBusinessIndicator
    get:
      consumes:
      - application/json
      description: get ProjectBusinessIndicator one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get ProjectBusinessIndicator one record
      tags:
      - ProjectBusinessIndicator
    put:
      consumes:
      - application/json
      description: edit ProjectBusinessIndicator one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: update ProjectBusinessIndicator form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/form.UpProjectBusinessIndicatorForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: edit ProjectBusinessIndicator one record
      tags:
      - ProjectBusinessIndicator
  /api/v1/project_business_indicators/batch:
    delete:
      consumes:
      - application/json
      description: delete ProjectBusinessIndicator list record
      parameters:
      - description: ProjectBusinessIndicator id list
        in: body
        name: ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: delete ProjectBusinessIndicator list record
      tags:
      - ProjectBusinessIndicator
    post:
      consumes:
      - application/json
      description: create ProjectBusinessIndicator batch record
      parameters:
      - description: 添加ProjectBusinessIndicator表单列表
        in: body
        name: '{}'
        required: true
        schema:
          items:
            $ref: '#/definitions/form.CreateProjectBusinessIndicatorForm'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: create ProjectBusinessIndicator batch record
      tags:
      - ProjectBusinessIndicator
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: get User batch record
      parameters:
      - description: Uid
        in: query
        name: uid
        type: string
      - description: Name
        in: query
        name: name
        type: string
      - description: page size
        in: query
        name: pageSize
        type: integer
      - description: page num
        in: query
        name: pageNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get User batch record
      tags:
      - User
    post:
      consumes:
      - application/json
      description: create User one record
      parameters:
      - description: 添加User表单
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/form.CreateUserForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: create User one record
      tags:
      - User
  /api/v1/users/:id:
    delete:
      consumes:
      - application/json
      description: delete User one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: delete User one record
      tags:
      - User
    get:
      consumes:
      - application/json
      description: get User one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: get User one record
      tags:
      - User
    put:
      consumes:
      - application/json
      description: edit User one record
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: update User form
        in: body
        name: '{}'
        required: true
        schema:
          $ref: '#/definitions/form.UpUserForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: edit User one record
      tags:
      - User
  /api/v1/users/batch:
    delete:
      consumes:
      - application/json
      description: delete User list record
      parameters:
      - description: User id list
        in: body
        name: ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: delete User list record
      tags:
      - User
    post:
      consumes:
      - application/json
      description: create User batch record
      parameters:
      - description: 添加User表单列表
        in: body
        name: '{}'
        required: true
        schema:
          items:
            $ref: '#/definitions/form.CreateUserForm'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: create User batch record
      tags:
      - User
swagger: "2.0"
